const CARD_RANKS = ["Ace", "2", "3", "4", "5", "6", "7", "8", "9", "10", "Jack", "Queen", "King"];
const CARD_SUITS = ["Clubs", "Diamonds", "Hearts", "Spades"];
const CARD_UI = [
	{ symbol: "🂠", name: "Back", unicode: "&#x1F0A0;" },
	{ symbol: "🂡", name: "Ace Of Spades", unicode: "&#x1F0A1;" },
	{ symbol: "🂢", name: "Two Of Spades", unicode: "&#x1F0A2;" },
	{ symbol: "🂣", name: "Three Of Spades", unicode: "&#x1F0A3;" },
	{ symbol: "🂤", name: "Four Of Spades", unicode: "&#x1F0A4;" },
	{ symbol: "🂥", name: "Five Of Spades", unicode: "&#x1F0A5;" },
	{ symbol: "🂦", name: "Six Of Spades", unicode: "&#x1F0A6;" },
	{ symbol: "🂧", name: "Seven Of Spades", unicode: "&#x1F0A7;" },
	{ symbol: "🂨", name: "Eight Of Spades", unicode: "&#x1F0A8;" },
	{ symbol: "🂩", name: "Nine Of Spades", unicode: "&#x1F0A9;" },
	{ symbol: "🂪", name: "Ten Of Spades", unicode: "&#x1F0AA;" },
	{ symbol: "🂫", name: "Jack Of Spades", unicode: "&#x1F0AB;" },
	{ symbol: "🂬", name: "Knight Of Spades", unicode: "&#x1F0AC;" },
	{ symbol: "🂭", name: "Queen Of Spades", unicode: "&#x1F0AD;" },
	{ symbol: "🂮", name: "King Of Spades", unicode: "&#x1F0AE;" },
	{ symbol: "🂱", name: "Ace Of Hearts", unicode: "&#x1F0B1;" },
	{ symbol: "🂲", name: "Two Of Hearts", unicode: "&#x1F0B2;" },
	{ symbol: "🂳", name: "Three Of Hearts", unicode: "&#x1F0B3;" },
	{ symbol: "🂴", name: "Four Of Hearts", unicode: "&#x1F0B4;" },
	{ symbol: "🂵", name: "Five Of Hearts", unicode: "&#x1F0B5;" },
	{ symbol: "🂶", name: "Six Of Hearts", unicode: "&#x1F0B6;" },
	{ symbol: "🂷", name: "Seven Of Hearts", unicode: "&#x1F0B7;" },
	{ symbol: "🂸", name: "Eight Of Hearts", unicode: "&#x1F0B8;" },
	{ symbol: "🂹", name: "Nine Of Hearts", unicode: "&#x1F0B9;" },
	{ symbol: "🂺", name: "Ten Of Hearts", unicode: "&#x1F0BA;" },
	{ symbol: "🂻", name: "Jack Of Hearts", unicode: "&#x1F0BB;" },
	{ symbol: "🂼", name: "Knight Of Hearts", unicode: "&#x1F0BC;" },
	{ symbol: "🂽", name: "Queen Of Hearts", unicode: "&#x1F0BD;" },
	{ symbol: "🂾", name: "King Of Hearts", unicode: "&#x1F0BE;" },
	{ symbol: "🃁", name: "Ace Of Diamonds", unicode: "&#x1F0C1;" },
	{ symbol: "🃂", name: "Two Of Diamonds", unicode: "&#x1F0C2;" },
	{ symbol: "🃃", name: "Three Of Diamonds", unicode: "&#x1F0C3;" },
	{ symbol: "🃄", name: "Four Of Diamonds", unicode: "&#x1F0C4;" },
	{ symbol: "🃅", name: "Five Of Diamonds", unicode: "&#x1F0C5;" },
	{ symbol: "🃆", name: "Six Of Diamonds", unicode: "&#x1F0C6;" },
	{ symbol: "🃇", name: "Seven Of Diamonds", unicode: "&#x1F0C7;" },
	{ symbol: "🃈", name: "Eight Of Diamonds", unicode: "&#x1F0C8;" },
	{ symbol: "🃉", name: "Nine Of Diamonds", unicode: "&#x1F0C9;" },
	{ symbol: "🃊", name: "Ten Of Diamonds", unicode: "&#x1F0CA;" },
	{ symbol: "🃋", name: "Jack Of Diamonds", unicode: "&#x1F0CB;" },
	{ symbol: "🃌", name: "Knight Of Diamonds", unicode: "&#x1F0CC;" },
	{ symbol: "🃍", name: "Queen Of Diamonds", unicode: "&#x1F0CD;" },
	{ symbol: "🃎", name: "King Of Diamonds", unicode: "&#x1F0CE;" },
	{ symbol: "🃏", name: "Black Joker", unicode: "&#x1F0CF;" },
	{ symbol: "🃑", name: "Ace Of Clubs", unicode: "&#x1F0D1;" },
	{ symbol: "🃒", name: "Two Of Clubs", unicode: "&#x1F0D2;" },
	{ symbol: "🃓", name: "Three Of Clubs", unicode: "&#x1F0D3;" },
	{ symbol: "🃔", name: "Four Of Clubs", unicode: "&#x1F0D4;" },
	{ symbol: "🃕", name: "Five Of Clubs", unicode: "&#x1F0D5;" },
	{ symbol: "🃖", name: "Six Of Clubs", unicode: "&#x1F0D6;" },
	{ symbol: "🃗", name: "Seven Of Clubs", unicode: "&#x1F0D7;" },
	{ symbol: "🃘", name: "Eight Of Clubs", unicode: "&#x1F0D8;" },
	{ symbol: "🃙", name: "Nine Of Clubs", unicode: "&#x1F0D9;" },
	{ symbol: "🃚", name: "Ten Of Clubs", unicode: "&#x1F0DA;" },
	{ symbol: "🃛", name: "Jack Of Clubs", unicode: "&#x1F0DB;" },
	{ symbol: "🃜", name: "Knight Of Clubs", unicode: "&#x1F0DC;" },
	{ symbol: "🃝", name: "Queen Of Clubs", unicode: "&#x1F0DD;" },
	{ symbol: "🃞", name: "King Of Clubs", unicode: "&#x1F0DE;" },
	{ symbol: "🃟", name: "White Joker", unicode: "&#x1F0DF;" }
];
const SUIT_SYMBOLS = ["♣︎", "♦", "♥︎", "♠︎", "🃏", "🃟"];

export { CARD_RANKS, CARD_SUITS, CARD_UI, SUIT_SYMBOLS };
